#if !defined(_RelatedWord_)
#define _RelatedWord_

#include "DataStore.h"

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class RelatedWord {
public:

    CText RG_PART_OF_SPEECH; // q(RG_PART_OF_SPEECH)
    CLong RG_ORDER; // q(RG_ORDER)
    CLong RGW_ID; // q(RGW_ID)
    CLong RG_ID; // q(RG_ID)
    CText RGW_WORD; // q(RGW_WORD)
    CText RGW_NOTE; // q(RGW_NOTE)
    CLong RGW_ORDER; // q(RGW_ORDER)
};

#endif // !defined(_RelatedWord_)