#if !defined(_Word_)
#define _Word_

#include "DataStore.h"

// This code was generated by a tool. Don't modify it manually.
// http://sqldalmaker.sourceforge.net

class Word {
public:

    CLong W_ID; // t(W_ID)
    CText W_WORD; // t(W_WORD)
};

#endif // !defined(_Word_)